name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    environment: ${{ (github.ref == 'refs/heads/main' && 'protected') || null }}
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Get appropriate base and head commit SHAs for `nx affected` commands
        uses: nrwl/nx-set-shas@v5

      - name: Install dependencies
        run: pnpm ci

      - name: Check code formatting
        run: pnpm nx record -- pnpm nx format:check --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}

      - name: Build, test, lint
        run: pnpm nx affected -t build e2e lint test typecheck --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}
