name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    environment: ${{ (github.ref == 'refs/heads/main' && 'protected') || null }}
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v7
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v6
        with:
          cache: true

      # This enables task distribution via Nx Cloud
      # Learn more at https://nx.dev/docs/reference/nx-cloud-cli#npx-nxcloud-startcirun
      - run: pnpm nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build,e2e,lint,test,typecheck"

      - run: pnpm ci

      - run: pnpm nx record -- pnpm nx format:check --base="remotes/origin/main"
      - run: pnpm nx affected --base="remotes/origin/main" -t build e2e lint test typecheck
