name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v6
        with:
          cache: true

      # This enables task distribution via Nx Cloud
      # Learn more at https://nx.dev/docs/reference/nx-cloud-cli#npx-nxcloud-startcirun
      - run: pnpm nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e"

      - run: pnpm ci

      # Prepend any command with "nx record --" to record its logs to Nx Cloud
      - run: pnpm nx record -- pnpm nx format:check --base="remotes/origin/main"
      - run: pnpm check
